name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: Android
            os: ubuntu-latest
            target: Android

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: Release
          target: ${{ matrix.config.target }}
          combine: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geode-build-${{ matrix.config.name }}
          path: build/*.geode
