name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Geode Mod
        # This action automatically installs Geode for you!
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: Release
          combine: true
